services:
  postgres:
    build:
      dockerfile: ./docker/postgresql/Dockerfile
    environment:
      - POSTGRES_DB=ideanick
      - POSTGRES_USER=ideanick
      - POSTGRES_PASSWORD=ideanick
    ports:
      - "5432:5432"
  app:
    # platform: linux/amd64 # uncomment to build for amd64 which used in heroku
    build:
      context: .
      # args used in image build as env variables
      args:
        # ${...} is used to get value from env of host machine
        SOURCE_VERSION: ${SOURCE_VERSION}
    image: ideanick-image
    container_name: ideanick-container
    # env_file and ports used in runtime of container, not in image build
    env_file:
      - ./webapp/.env
      - ./backend/.env
      - ./.env.docker
    ports:
      - '${PORT}:${PORT}'     
